# Generated by Django 5.2.10 on 2026-01-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='back_image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='front_image',
        ),
        migrations.AddField(
            model_name='studysession',
            name='is_practice_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.deck'),
        ),
        migrations.AlterModelTable(
            name='card',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cardreview',
            table=None,
        ),
        migrations.AlterModelTable(
            name='deck',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studysession',
            table=None,
        ),
    ]
