# Generated by Django 5.2.10 on 2026-01-30 06:35

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_back_image_remove_card_front_image_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
