# Generated by Django 5.2.10 on 2026-01-30 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['next_review'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='cardreview',
            options={'ordering': ['-reviewed_at'], 'verbose_name': 'Отзыв о карточке', 'verbose_name_plural': 'Отзывы о карточках'},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['-created_at'], 'verbose_name': 'Колода', 'verbose_name_plural': 'Колоды'},
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Сессия обучения', 'verbose_name_plural': 'Сессии обучения'},
        ),
        migrations.AddField(
            model_name='deck',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичная'),
        ),
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='ease_factor',
            field=models.FloatField(default=2.5, verbose_name='Фактор легкости'),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='card',
            name='interval',
            field=models.IntegerField(default=0, verbose_name='Интервал (дни)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='Приостановлена'),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее повторение'),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующее повторение'),
        ),
        migrations.AlterField(
            model_name='card',
            name='repetitions',
            field=models.IntegerField(default=0, verbose_name='Повторения'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='ease_factor_after',
            field=models.FloatField(default=2.5, verbose_name='EF после'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='ease_factor_before',
            field=models.FloatField(default=2.5, verbose_name='EF до'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='interval_after',
            field=models.IntegerField(default=0, verbose_name='Интервал после'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='interval_before',
            field=models.IntegerField(default=0, verbose_name='Интервал до'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='rating',
            field=models.IntegerField(verbose_name='Оценка (1-4)'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='time_taken',
            field=models.IntegerField(default=0, verbose_name='Время (сек)'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='cards_correct',
            field=models.IntegerField(default=0, verbose_name='Правильных ответов'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='cards_studied',
            field=models.IntegerField(default=0, verbose_name='Изучено карточек'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='cards.deck'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='is_practice_mode',
            field=models.BooleanField(default=False, verbose_name='Режим практики'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='points_earned',
            field=models.IntegerField(default=0, verbose_name='Заработано очков'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Цвет')),
                ('icon', models.CharField(default='📁', max_length=50, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='cards.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ['name'],
                'unique_together': {('user', 'name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='cards.folder'),
        ),
    ]
