# Generated by Django 5.2.10 on 2026-02-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_options_alter_cardreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/images/', verbose_name='Изображение ответа'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('basic', 'Обычная'), ('multiple_choice', 'Множественный выбор'), ('matching', 'Подбор')], default='basic', max_length=20, verbose_name='Тип карточки'),
        ),
        migrations.AddField(
            model_name='card',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/images/', verbose_name='Изображение вопроса'),
        ),
        migrations.AddField(
            model_name='card',
            name='options',
            field=models.JSONField(blank=True, default=list, verbose_name='Варианты ответа'),
        ),
    ]
