# Generated by Django 5.2.10 on 2026-02-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_back_image_card_card_type_card_front_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='back_image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='front_image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='options',
        ),
    ]
