# Generated by Django 5.2.10 on 2026-02-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_card_back_image_remove_card_card_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='is_practice_mode',
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('basic', 'Обычная'), ('multiple_choice', 'Множественный выбор')], default='basic', max_length=20, verbose_name='Тип карточки'),
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение будет показано вместе с вопросом', null=True, upload_to='cards/images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='is_random_order',
            field=models.BooleanField(default=False, verbose_name='Случайный порядок'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='is_reversed',
            field=models.BooleanField(default=False, verbose_name='Реверс (ответ → вопрос)'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='mode',
            field=models.CharField(choices=[('learning', 'Обучение'), ('practice', 'Тренировка'), ('matching', 'Подбор'), ('test', 'Тест')], default='learning', max_length=20, verbose_name='Режим'),
        ),
    ]
