# Generated by Django 5.2.10 on 2026-02-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_remove_studysession_is_practice_mode_card_card_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='is_random_order',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='is_reversed',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='mode',
        ),
        migrations.AddField(
            model_name='studysession',
            name='is_practice_mode',
            field=models.BooleanField(default=False, verbose_name='Режим практики'),
        ),
    ]
