# Generated by Django 5.2.10 on 2026-02-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_card_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='card',
            new_name='cards_card_next_re_da4ff1_idx',
            old_name='cards_card_next_re_ix',
        ),
        migrations.RenameIndex(
            model_name='card',
            new_name='cards_card_deck_id_e67f8f_idx',
            old_name='cards_card_deck_next_ix',
        ),
    ]
