# Generated by Django 5.2.10 on 2026-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studypet',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Имя питомца'),
        ),
    ]
